<section>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Upload</h3>
                </div>
                <div class="panel-body">
                    <?php if ($this->error): ?>
                        <p class="error"> <?= $message; ?> </p>
                    <?php endif ?>
                    <?php
                        $formUpload = $this->formUpload;
                        echo $this->form()->openTag($formUpload);
                    ?>
                    <div class="control-group">
                        <?=$this->formLabel($formUpload->get('file')); ?>
                        <div class="controls">
                            <?= $this->formElement($formUpload->get('file'));?>
                            <?= $this->formElementErrors($formUpload->get('file')); ?>
                        </div>
                    </div>
                    <div class="control-label pull-left">
                        <?= $this->formElement($formUpload->get('submit'));?>
                    </div>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</section>