<div class="row">


<?php
    foreach($files as $file) :
?>
        <div class="col-md-6">

<div class="thumbnail">
    <img src="<?=$file['path']; ?>">
    <!--div class="caption">
        <h3>Thumbnail label</h3>
        <p><?=$_SESSION['profile_name']?></p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
    </div-->
</div>

        </div>
<?php endforeach ?>


</div>