<section>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Email</h3>
                </div>
                <div class="panel-body">
                    <?php if ($this->error): ?>
                        <p class="error"> <?= $message; ?> </p>
                    <?php endif ?>
                    <?php
                        $formEmail = $this->formEmail;
                        echo $this->form()->openTag($formEmail);
                    ?>
                    <div class="control-group">
                        <?=$this->formLabel($formEmail->get('email_current')); ?>
                        <div class="controls">
                            <?= $this->formElement($formEmail->get('email_current'));?>
                            <?= $this->formElementErrors($formEmail->get('email_current')); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?=$this->formLabel($formEmail->get('email')); ?>
                        <div class="controls">
                            <?= $this->formElement($formEmail->get('email'));?>
                            <?= $this->formElementErrors($formEmail->get('email')); ?>
                        </div>
                    </div>
                    <div class="control-label pull-left">
                        <?= $this->formElement($formEmail->get('submit'));?>
                    </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Password</h3>
                </div>
                <div class="panel-body">
                    <?php if ($this->error): ?>
                        <p class="error"> <?= $message; ?> </p>
                    <?php endif ?>
                    <?php
                    $formPassword = $this->formPassword;
                    echo $this->form()->openTag($formPassword);
                    ?>
                    <div class="control-group">
                        <?=$this->formLabel($formPassword->get('password_current')); ?>
                        <div class="controls">
                            <?= $this->formElement($formPassword->get('password_current'));?>
                            <?= $this->formElementErrors($formPassword->get('password_current')); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?=$this->formLabel($formPassword->get('password')); ?>
                        <div class="controls">
                            <?= $this->formElement($formPassword->get('password'));?>
                            <?= $this->formElementErrors($formPassword->get('password')); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?=$this->formLabel($formPassword->get('confirm_password')); ?>
                        <div class="controls">
                            <?= $this->formElement($formPassword->get('confirm_password'));?>
                            <?= $this->formElementErrors($formPassword->get('confirm_password')); ?>
                        </div>
                    </div>
                    <div class="control-label pull-left">
                        <?= $this->formElement($formPassword->get('submit'));?>
                    </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Other</h3>
                </div>
                <div class="panel-body">
                    <?php if ($this->error): ?>
                        <p class="error"> <?= $message; ?> </p>
                    <?php endif ?>
                    <?php
                    $formOther = $this->formOther;
                    echo $this->form()->openTag($formOther);
                    ?>
                    <div class="control-group">
                        <?=$this->formLabel($formOther->get('full_name')); ?>
                        <div class="controls">
                            <?= $this->formElement($formOther->get('full_name'));?>
                            <?= $this->formElementErrors($formOther->get('full_name')); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?=$this->formLabel($formOther->get('bio')); ?>
                        <div class="controls">
                            <?= $this->formElement($formOther->get('bio'));?>
                            <?= $this->formElementErrors($formOther->get('bio')); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?=$this->formLabel($formOther->get('link_skype')); ?>
                        <div class="controls">
                            <?= $this->formElement($formOther->get('link_skype'));?>
                            <?= $this->formElementErrors($formOther->get('link_skype')); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?=$this->formLabel($formOther->get('link_site')); ?>
                        <div class="controls">
                            <?= $this->formElement($formOther->get('link_site'));?>
                            <?= $this->formElementErrors($formOther->get('link_site')); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?=$this->formLabel($formOther->get('link_vk')); ?>
                        <div class="controls">
                            <?= $this->formElement($formOther->get('link_vk'));?>
                            <?= $this->formElementErrors($formOther->get('link_vk')); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?=$this->formLabel($formOther->get('link_fb')); ?>
                        <div class="controls">
                            <?= $this->formElement($formOther->get('link_fb'));?>
                            <?= $this->formElementErrors($formOther->get('link_fb')); ?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?=$this->formLabel($formOther->get('link_tw')); ?>
                        <div class="controls">
                            <?= $this->formElement($formOther->get('link_tw'));?>
                            <?= $this->formElementErrors($formOther->get('link_tw')); ?>
                        </div>
                    </div>

                    <div class="control-label pull-left">
                        <?= $this->formElement($formPassword->get('submit'));?>
                    </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
</section>