<section class="Login">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Login</h3>
                </div>
                <div class="panel-body">
                    <?php if ($this->error): ?>
                        <p class="error">
                            There were one or more issues with your submission.
                            Please correct them as indicated below.
                        </p>
                    <?php endif ?>

                    <?php
                        $formLogin = $this->formLogin;
                        echo $this->form()->openTag($formLogin);
                    ?>

                    <div class="control-group">
                        <?=$this->formLabel($formLogin->get('profile_name')); ?>
                        <div class="controls">
                            <?= $this->formElement($formLogin->get('profile_name'));?>
                        </div>
                    </div>
                    <div class="control-group">
                        <?=$this->formLabel($formLogin->get('password')); ?>
                        <div class="controls">
                            <?= $this->formElement($formLogin->get('password'));?>
                        </div>
                    </div>
                    <div class="control-label pull-left">
                        <?= $this->formElement($formLogin->get('submit'));?>
                    </div>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>
</section>