<div class="jumbotron" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-md-2 col-md-offset-0">
            <img src="/img/avatar.png" alt="..." class="img-circle avatar-edit center-block">
        </div>

        <div class="col-md-8 col-md-offset-0">
            <h1>
                <span class="zf-green">
                    <?php echo $profile_name; ?>
                </span>
            </h1>
            <div class="btn-group" role="group" aria-label="...">
                <div class="btn disabled">Photos <span class="badge">0</span></div>
                <div class="btn disabled">Following <span class="badge">0</span></div>
                <div class="btn disabled">Followers <span class="badge">0</span></div>
            </div>
            <div>
                <a class="btn btn-success" href="/<?= $_SESSION['profile_name']?>">Flow <span class="glyphicon glyphicon-picture" aria-hidden="true"></span></a>
                <a class="btn btn-success" href="/<?= $_SESSION['profile_name']?>/about">About <span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
                <a class="btn btn-success" href="/files/upload">Upload <span class="glyphicon glyphicon-open" aria-hidden="true"></span></a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <?php foreach($files as $file) : ?>
        <div class="col-md-4">
            <div  class="thumbnail">
            <a href="/files/view/<?= $file['name']; ?>">
                <img src="<?=$file['folder']. $file['name']. $file['ext']; ?>">
            </a>
            <div class="btn-group" role="group" aria-label="...">
                <div class="btn disabled"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> <?= $file['likes']; ?></div>
                <div class="btn disabled"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> <?= $file['comments']; ?></div>
            </div>
            </div>
        </div>
    <?php endforeach ?>
</div>